### ISSUE TITLE
Remove `refMap`

### ISSUE THREAD

**Issue by marbemac** [stoplightio/json-ref-resolver#118]
**Chore summary**

Now that we the dependency graph is exposed on the resolved result (json-ref-resolver v3), we can remove `refMap`. As far as I can tell, the graph tracks all the same data as refMap (and more).

**Comment by philsturgeon** [comment]
@marbemac this seems like something which might fall through the cracks. Do you know who could work on it, and is this just tech debt, or is this likely to be a performance improvement?

**Comment by philsturgeon** [comment]
@P0lip is this one still a thing?

**Comment by P0lip** [comment]
@marbemac Yeah, it's still hasn't been removed.

> . Do you know who could work on it, and is this just tech debt, or is this likely to be a performance improvement?

It's a tech debt. We introduced a more powerful feature instead (graph), and refMap is simply no longer needed, as graph contains everything plus much more.

**Comment by lottamus** [comment]
We're actually using the refMap in @stoplight/elements to build up the vis graph so I suggest we keep it: https://github.com/stoplightio/elements/blob/master/src/hooks/useComputeVisGraph.tsx#L103
