### ISSUE TITLE
Add a CLI for dereferencing and bundling

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/json-ref-resolver#169]
**User story.**
As devops, I am trying to create a pipeline to spit out an all-in-one YAML specification, following the same rules and edge cases as Studio, Spectral, etc.

**Is your feature request related to a problem?**
json ref resolver does not have a CLI so I cannot use it programmatically without wrapping it in a node script.

**Describe the solution you'd like**

```
{bin} deref openapi.yaml [--output=output.yaml] [--reader=file|http|https|custom-filepath.js]
```

When we solve bundle logic, me can add a command for that too:

```
{bin} bundle [--output=output.yaml] [--reader=file|http|https|custom-filepath.js]
```

The bin name could be `jsr` to save keyboard expiration. 

**Additional context**

https://twitter.com/enigmamaker/status/1217727601369919488

**Comment by braco** [comment]
@philsturgeon you closed this, what solution did you find?

**Comment by philsturgeon** [comment]
json-ref-resolver was shelved in place of https://github.com/APIDevTools/json-schema-ref-parser, which has a CLI already: https://github.com/APIDevTools/swagger-cli/
