### ISSUE TITLE
Type error: Cannot find namespace 'uri'

### ISSUE THREAD

**Issue by adanilev** [stoplightio/json-ref-resolver#207]
**Describe the bug**
Building TS projects with this as a dependency fail with several errors like this:
```
node_modules/@stoplight/json-ref-resolver/types.d.ts:10:57 - error TS2503: Cannot find namespace 'uri'.
```

I tried adding @types/urijs as suggested in #33 but no luck.

**To Reproduce**

1. Clone https://github.com/adanilev/stoplight-uri-issue
1. Run `yarn && yarn tsc`

**Expected behavior**
No errors should occur.

**Environment (remove any that are not applicable):**
 - OS: macOS 10.15.3
- yarn: 1.17.3
- Typescript: 3.8.3

**Additional context**
I'm trying to build a project that includes spectral and this is a dependency of that.

**Comment by adanilev** [comment]
If anyone else encounters, one workaround is to create a file with this:
```ts
declare namespace uri {
  export type URI = any;
}
```

**Comment by im-shyam** [comment]
I still face the same issue. Not sure what I'm doing wrong.

**Comment by P0lip** [comment]
@im-shyam are you using 3.0.9v?

**Comment by im-shyam** [comment]
Yes and I resolved it by adding the file with @adanilev had suggested. 
```
    "@stoplight/spectral": "^5.4.0",
    "tslib": "^1.13.0",
    "typescript": "^3.9.7",
    "@types/node": "^14.0.23"
```
dependencies list for your reference if this helps.

**Comment by aditya748** [comment]
@im-shyam @P0lip 

It starts giving me the same error again if I try to add any other interface

for Example:

`import { IFunctionResult } from "@stoplight/spectral/dist/types/function";

declare namespace uri {
  export type URI = any;
}

declare namespace validator {
  export type URI =
    | void
    | IFunctionResult[]
    | Promise<void | IFunctionResult[]>;
}
`

**Comment by P0lip** [comment]
@aditya748 
I think this might be caused by the fact Spectral@5.4.0 uses the older json-ref-resolver.
Could you try out the latest 5.5.0 beta to see whether the same error still persists?
