### ISSUE TITLE
Emphasize deprecation notice

### ISSUE THREAD

**Issue by pushred** [stoplightio/json-ref-resolver#210]
Ahhh, my team spent some time going down the path of using this library (and encountering some strange issues) before noticing:

![CleanShot 2020-09-14 at 14 24 07](https://user-images.githubusercontent.com/431435/93123472-284ec680-f696-11ea-8778-f4ea2b05e921.png)

:grimacing:

GitHub's recent design updates that moved the description to a sidebar didn't help but please consider adding a more prominent notice to the README. Also [`npm deprecate`](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions) for good measure and further emphasis on npmjs.com

Then again, perhaps nobody else is noticing this library! I think I found it by searching npmjs.com with the terms "json ref resolver" and automatically went to the Stoplight result because I trust Stoplight.

However had I searched just with "json ref" I would have found two results for the successor library, https://www.npmjs.com/package/@apidevtools/json-schema-ref-parser

https://twitter.com/philsturgeon/status/1235849451568152577

**Comment by philsturgeon** [comment]
@pushred doh! Thanks for pointing this out. We'll pull all the levers we have available to us to make it more clear that this repo is no longer a thing, including NPM deprecation, archiving on GitHub, and anything else we think up. We didn't do that for a while to avoid spamming users of our tools (which had not all moved across) with deprecation warnings, but it's time to get on with it. Going to close this and hit archive now!
