### ISSUE TITLE
error TS2688: Cannot find type definition file for 'urijs'

### ISSUE THREAD

**Issue by Gnouks** [stoplightio/json-ref-resolver#33]
Hello,

I try to use json-ref-resolver. I have installed the module with yarn.
Here is what II obtain when I compile my program.

Any idea please ?
Thanks

Date: 2019-05-07T14:18:17.192Z
Hash: 42123c479fcdf76ec2c5
Time: 49760ms
chunk {main} main.js, main.js.map (main) 1.87 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 92.1 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 1.35 MB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 3.93 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]

ERROR in node_modules/@stoplight/json-ref-resolver/resolver.d.ts(1,23): error TS2688: Cannot find type definition file for 'urijs'.
node_modules/@stoplight/json-ref-resolver/resolver.d.ts(12,73): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/runner.d.ts(1,23): error TS2688: Cannot find type definition file for 'urijs'.
node_modules/@stoplight/json-ref-resolver/runner.d.ts(6,25): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/runner.d.ts(17,72): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/runner.d.ts(23,57): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/runner.d.ts(26,14): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(1,23): error TS2688: Cannot find type definition file for 'urijs'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(10,57): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(18,17): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(29,15): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(34,22): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(35,22): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(45,10): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(56,11): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(57,16): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(64,16): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(81,10): error TS2503: Cannot find namespace 'uri'.
node_modules/@stoplight/json-ref-resolver/types.d.ts(102,44): error TS2503: Cannot find namespace 'uri'.

**Comment by marbemac** [comment]
Hi @Gnouks - we'll fix this up, but in the meantime you can add `@types/urijs` to your dev dependencies and it should resolve (heh) the issue.

**Comment by XVincentX** [comment]
@marbemac Do you want to add the types as a dependency? 🤔

**Comment by marbemac** [comment]
This should be fixed in 1.5.1 - please drop a note if you're still running into trouble!
